on:
  workflow_call:

name: 'terraform fmt'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup terraform
      run: |
        brew install tfenv
        tfenv install
    - name: terraform fmt
      run: terraform fmt -check -diff -recursive
